# Site settings
title: Bobblehead Portfolio
description: Track your Bobblehead product investments and performance
baseurl: "/bobblehead-portfolio" # subpath of your site, e.g. /portfolio
url: "https://futuregadgettemplates.github.io" # the base hostname & protocol for your site

# Google Sheets URLs
sheets:
  published: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTz3g-6RurBxIs_Hcc4yvaBGBRgTX85B1negAEgMl456sVC-Qa-QiszWn3Cf1SbJPTtyiZ7CegOdKbv/pubhtml"
  edit: "https://docs.google.com/spreadsheets/d/1ojSAoCAx-q0arCh-1dfth145V9XDzcPJDCArhXtONFc/edit?usp=sharing"
#  collectr: ""
  transactions: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTz3g-6RurBxIs_Hcc4yvaBGBRgTX85B1negAEgMl456sVC-Qa-QiszWn3Cf1SbJPTtyiZ7CegOdKbv/pub?gid=0&single=true&output=tsv"
  holdings: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTz3g-6RurBxIs_Hcc4yvaBGBRgTX85B1negAEgMl456sVC-Qa-QiszWn3Cf1SbJPTtyiZ7CegOdKbv/pub?gid=1563230874&single=true&output=tsv"
  sales: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTz3g-6RurBxIs_Hcc4yvaBGBRgTX85B1negAEgMl456sVC-Qa-QiszWn3Cf1SbJPTtyiZ7CegOdKbv/pub?gid=845485488&single=true&output=tsv"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - .claude
  - "*.md~"
  - guide

# Collections (if needed in future)
collections_dir: collections

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
